- name: install nginx
  hosts: frountend
  become: yes
  tasks:
  - name: install nginx
    ansible.buidin.packages:
      name: nginx
      state: present
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes
      