- name: uninstall nginx
  hosts: frountend
  become: yes
  tasks:
  - name: stop nginx
    ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: no
  - name: uninstall
    package:
      name: nginx
      state: absent
    